SELECT 
    SUCURSAL_ID, 
    PRODUCTO_ID, 
    COUNT(CANTIDAD_PRODUCTO), 
    SUM(MONTO)
FROM VENTAS
GROUP BY SUCURSAL_ID,PRODUCTO_ID
ORDER BY 1;


SELECT  SUCURSAL_ID,
        PRODUCTO_ID,
        COUNT(CANTIDAD_PRODUCTO),
        SUM(MONTO)
FROM VENTAS
GROUP BY CUBE(SUCURSAL_ID,PRODUCTO_ID)
ORDER BY 1;


SELECT 
        DECODE (GROUPING (SUCURSAL_ID), 1, 'Todos', SUCURSAL_ID) AS SUCURSAL_ID,
        DECODE (GROUPING (PRODUCTO_ID), 1, 'Todos', PRODUCTO_ID) AS producto_id,
        COUNT(CANTIDAD_PRODUCTO),
        SUM(MONTO)
FROM VENTAS
GROUP BY CUBE(SUCURSAL_ID,PRODUCTO_ID)
ORDER BY 1;


